version: "2"
checks:
  method-complexity:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 100
plugins:
  eslint:
    enabled: true
exclude_patterns:
  - "**/node_modules/"
  - "**/*.d.ts"
