checks:
  method-complexity:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 100
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
  eslint:
    enabled: true
    channel: eslint-6
  fixme:
    enabled: true
ratings:
  paths:
    - "*.ts"
    - "src/*.ts"
    - "test/*.ts"
